### ISSUE TITLE
Ability to handle folder creation with related files

### ISSUE THREAD

**Issue by vilic** [qiu8310/dot-template#3]
Workflow to adapt:

1. Create a component folder.
2. Automatically create an `index.ts`.
3. Automatically create a `folder-name.tsx` under the component folder, and add the reference to `index.ts`.

Another similar workflow:

1. Create a module/component `foo.tsx` under a folder with `index.ts`.
2. Automatically fill the template content into `foo.tsx` (which is already achievable).
3. Add the reference to `index.ts` (conditionally).

Put let me know if it's already achievable.

Thanks!

**Comment by qiu8310** [comment]
Hi, sorry for the late reply, I'm currently build another project, so didn't see this. sorry again.

I don't know how to explain to you, but I made a example for you can try this yourself.  It also helps with #2 .

If you have any more questions, please let me know.

**Comment by qiu8310** [comment]
By the way, I did not realize you second workflow, because I don't know the second step `2. Automatically fill the template content.`   which template content I should fill.

But I think if you understand the example I make,  the second workflow is also achievable.

**Comment by vilic** [comment]
Hi, thanks for the information! So strange I didn't even notice that the default export is a function...

Yes I think it solves those problems (at least makes them hackable).

I am encountering a situation that file system watching is not working, will investigate and see if I can get a minimal case.

**Comment by qiu8310** [comment]
@vilic  I understand your second workflow now, what's your want is inject reference to the `index.ts` file. you can config a `inject` field in `dtpl.ts` file and add some code fragment to the `index.ts` file.

I update the example above.

By the way, about your vscode `file system watching is not working` problem, maybe you can try to update your vscode.

**Comment by vilic** [comment]
@qiu8310 It's actually a bug caused by `!` in `.gitignore`, see the new issue I just created. Cheers!
