### ISSUE TITLE
command 'dot-template-vscode.createTemplateFiles' not found

### ISSUE THREAD

**Issue by Allenice** [qiu8310/dot-template#6]
执行命令 cmd + k, cmd +p 后， 提示：command 'dot-template-vscode.createTemplateFiles' not found
使用 minapp-cli 创建的项目已经有 .dtpl 文件夹，然后在 pages 文件夹里面新建页面，对应的文件没有生成

**Comment by qiu8310** [comment]
minapp 中不是这样用的，在 minapp 中只需要你新建一个 **文件夹**，就自动会帮帮你把文件夹里相关的文件创建好，不需要手动执行命令


如果想要手动执行命令，需要你修改 .dtpl/dtpl.js 这个文件。因为现在没有绑定任何模板文件，只绑定了 page 和 component 文件夹，要了解更多关于 dot-template 的功能可以看这里 https://github.com/qiu8310/dot-template/blob/master/ARTICLE_ABOUT_IT.md
